version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: rails-api-test

    parallelism: 1
    working_directory: ~/demo-rc-app

    steps:
      - checkout
      - run:
          name: install depencies
          command: |
            sudo gem update --system
            gem install bundler:2.1.4
            bundle install --jobs=4 --retry=3 --path demo-rc-app/bundle

      - run: sudo apt install -y postgresql-client || true

      - save_cache:
          paths:
            - ./demo-rc-app/bundle
          key: demo-rc-app-v1-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run: 
            name: Set up DB
            command: |
              bundle exec rake db:create db:schema:load --trace
              bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://postgres@localhost:5432/rails-api-test"

      - run:
          name: Parallel RSpec
          command: bin/rails test

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
